/**
 * Real elev8temedia roster + SOP playbooks, imported from the v7.6 localStorage
 * prototype at https://elev8temedia.netlify.app/. This mirrors the seed in
 * `supabase/migrations/20260622120000_agency_crm.sql` and is used as a render
 * fallback when the database has not been provisioned yet (see
 * `lib/data/agency.ts`).
 *
 * Weekly metrics and feedback start empty in the source (team-entered data), so
 * they are intentionally empty here too — the UI shows honest empty states.
 */

import type {
  AgencyClient,
  ClientFeedback,
  ClientWeeklyMetric,
  Sop,
  SopCategory,
} from "@/lib/types/agency";

export const agencyClients: AgencyClient[] = [
  {
    id: "time-is-wealth-usa",
    name: "Time Is Wealth USA",
    status: "Active",
    service: "META",
    contact: "Luis Garcia",
    email: "luis@timeiswealth.co",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 5,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 3.5,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#FFF7E6", accent: "#B45309", initial: "#FFE4A8" },
  },
  {
    id: "same-24-hours",
    name: "Same 24 Hours",
    status: "Active",
    service: "SMS",
    contact: "Tykwon Wade",
    email: "same24hoursapparel@gmail.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 0,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote:
      "SMS-only client. 10% of Postscript-attributed revenue only. No Meta tracking, no Shopify cut.",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#E6F4FF", accent: "#1D4ED8", initial: "#BFDBFE" },
  },
  {
    id: "dos-santos",
    name: "Dos Santos Collective",
    status: "Active",
    service: "META",
    contact: "Louis Dos Santos",
    email: "Dossantoscollective@gmail.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 3.5,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#FFEEF0", accent: "#BE185D", initial: "#FBCFE8" },
  },
  {
    id: "holy-spirit-co",
    name: "Holy Spirit Co",
    status: "Active",
    service: "SMS",
    contact: "Christian Graves",
    email: "hspiritclothing@gmail.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 0,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#F3EBFF", accent: "#6D28D9", initial: "#DDD6FE" },
  },
  {
    id: "art-shordy",
    name: "Art Shordy",
    status: "Active",
    service: "META",
    contact: "Tievin Walker",
    email: "shordy@artshordy.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 3.5,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#FFF0E6", accent: "#C2410C", initial: "#FED7AA" },
  },
  {
    id: "forever-situated",
    name: "Forever Situated",
    status: "Active",
    service: "META",
    contact: "Jahlil",
    email: "foreversituated60@gmail.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 3.5,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#EBFAEF", accent: "#047857", initial: "#A7F3D0" },
  },
  {
    id: "umbra-rare",
    name: "Umbra Rare",
    status: "Active",
    service: "META",
    contact: "Alberto Flores",
    email: "umbrareclothing@gmail.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 3.5,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#EBF1FA", accent: "#374151", initial: "#CBD5E1" },
  },
  {
    id: "outflow-clothing",
    name: "Outflow Clothing",
    status: "Active",
    service: "META",
    contact: "Brady Lemon",
    email: "outflowandclothing@gmail.com",
    channel: "WhatsApp",
    profitMargin: 60,
    feeOnRevenue: 10,
    feeOnProfit: 0,
    billingDay: 1,
    targetRevenue: 0,
    targetRoas: 3.5,
    nextDropDate: null,
    nextDropName: null,
    nextDropTime: null,
    profileNote: "",
    notes: "",
    archived: false,
    logoUrl: null,
    theme: { bg: "#FFF4F0", accent: "#9F1239", initial: "#FECDD3" },
  },
];

export const sopCategories: SopCategory[] = [
  { id: "onboarding", name: "Onboarding", emoji: "📥", bg: "#EEEDFE", accent: "#3C3489", initial: "#CECBF6" },
  { id: "client-calls", name: "Client Calls", emoji: "📞", bg: "#E6F1FB", accent: "#0C447C", initial: "#B5D4F4" },
  { id: "drop-days", name: "Drop Days", emoji: "🚀", bg: "#FAECE7", accent: "#712B13", initial: "#F5C4B3" },
  { id: "client-reads", name: "Client Reads", emoji: "🧠", bg: "#EAF3DE", accent: "#27500A", initial: "#C0DD97" },
];

export const sops: Sop[] = [
  {
    id: "sop_new_client",
    title: "New client setup",
    categoryId: "onboarding",
    steps: [
      {
        id: "sop_new_client-s1",
        key: "s1",
        body: "Send welcome email within 24 hours of signed contract",
        checked: false,
        template:
          "Hey [name],\n\nStoked to have you on the Elevate Media roster. I'm Orlando, COO. Quick rundown of next steps:\n\n1. I'll drop a Dropbox folder for our shared assets\n2. We lock in a 30-min kickoff call within the week\n3. By call time, you'll get an intake sheet to fill out\n\nReply with your best email for the Dropbox invite and 3 time slots that work this week. Let's get to it.\n\nOrlando",
      },
      { id: "sop_new_client-s2", key: "s2", body: "Create Dropbox folder named after the brand", checked: false, template: null },
      { id: "sop_new_client-s3", key: "s3", body: "Add client to ClickUp Active Roster board", checked: false, template: null },
      { id: "sop_new_client-s4", key: "s4", body: "Update CLAUDE.md with the new client in the Active Clients list", checked: false, template: null },
      { id: "sop_new_client-s5", key: "s5", body: "Create Context and Call Recap subfolders inside the client folder", checked: false, template: null },
      { id: "sop_new_client-s6", key: "s6", body: "Schedule kickoff call (Calendly link or WhatsApp it)", checked: false, template: null },
      {
        id: "sop_new_client-s7",
        key: "s7",
        body: "Send confirmation message after call is booked",
        checked: false,
        template:
          "Locked in. Kickoff call set for [day] at [time] EST. Link in your inbox.\n\nBefore the call:\n- Fill out the intake sheet I sent\n- Send over any existing creative, brand guides, or analytics access\n\nTalk soon.",
      },
      { id: "sop_new_client-s8", key: "s8", body: "Review intake form 24 hours before call so you walk in prepped", checked: false, template: null },
    ],
  },
  {
    id: "sop_discovery_call",
    title: "Discovery call agenda",
    categoryId: "client-calls",
    steps: [
      { id: "sop_discovery_call-s1", key: "s1", body: "Pre-call prep: 5 minutes researching their Instagram, website, last 3 drops", checked: false, template: null },
      { id: "sop_discovery_call-s2", key: "s2", body: "Open with rapport. Where they at, how their week is going. Keep it human.", checked: false, template: null },
      { id: "sop_discovery_call-s3", key: "s3", body: "Hard numbers: ask for current AOV, monthly revenue, profit margin, biggest expense", checked: false, template: null },
      { id: "sop_discovery_call-s4", key: "s4", body: "Identify the biggest 90-day problem. Could be revenue, retention, creative, ops. Pick the one.", checked: false, template: null },
      { id: "sop_discovery_call-s5", key: "s5", body: "Walk through the percentage model. We only get paid when they get paid. Match risk on both sides.", checked: false, template: null },
      { id: "sop_discovery_call-s6", key: "s6", body: "Lock cadence and comms channel. Weekly WhatsApp check-in or biweekly Zoom. Their pick.", checked: false, template: null },
      {
        id: "sop_discovery_call-s7",
        key: "s7",
        body: "Send recap message within 2 hours of call ending",
        checked: false,
        template:
          "Hey [name],\n\nStoked we got on. Quick recap of what we covered:\n\nPain point: [biggest 90-day problem]\nWhat we're attacking first: [angle]\nNext step from your side: [intake form / pixel access / brand guide]\nNext step from mine: [avatar blueprint / creative brief]\n\nI'll have [deliverable] in your inbox by [day]. Talk soon.\n\nOrlando",
      },
    ],
  },
  {
    id: "sop_drop_day",
    title: "Drop day timeline",
    categoryId: "drop-days",
    steps: [
      { id: "sop_drop_day-s1", key: "s1", body: "T-7 days: confirm exact drop date and time with client. Lock it in EST.", checked: false, template: null },
      { id: "sop_drop_day-s2", key: "s2", body: "T-5 days: lock creative and copy. No more changes after this.", checked: false, template: null },
      { id: "sop_drop_day-s3", key: "s3", body: "T-3 days: final review call with client. Walk through every asset, every message.", checked: false, template: null },
      {
        id: "sop_drop_day-s4",
        key: "s4",
        body: "T-2 days: schedule SMS blast in Postscript for exact drop time",
        checked: false,
        template: "Drop incoming.\n\n[Product] live tomorrow at [time] EST.\n\nLimited run. Set your alarm.\n\nLink locked until launch.",
      },
      { id: "sop_drop_day-s5", key: "s5", body: "T-1 day: test SMS flow with internal numbers. Confirm pixel firing.", checked: false, template: null },
      {
        id: "sop_drop_day-s6",
        key: "s6",
        body: "T-0 launch hour: fire SMS blast at exact drop time",
        checked: false,
        template: "It's live.\n\n[Product] available now.\n[link]\n\nLimited drop. Don't sleep.",
      },
      { id: "sop_drop_day-s7", key: "s7", body: "T+1 hour: monitor for technical issues. Site speed, checkout flow, pixel.", checked: false, template: null },
      { id: "sop_drop_day-s8", key: "s8", body: "T+2 days: pull 24-hour and 48-hour performance numbers", checked: false, template: null },
      {
        id: "sop_drop_day-s9",
        key: "s9",
        body: "T+3 days: send post-launch report",
        checked: false,
        template:
          "Drop recap.\n\nRevenue: [X]\nROAS: [X]\nSMS open rate: [X]\nClick rate: [X]\nKillers: [the angle/creative/segment that performed best]\nLosers: [what to cut next drop]\n\nNext drop prep starts [date]. Talk soon.",
      },
    ],
  },
];

/** Source seed has no team-entered weekly metrics yet. */
export const clientWeeklyMetrics: ClientWeeklyMetric[] = [];

/** Source seed has no logged feedback yet. */
export const clientFeedback: ClientFeedback[] = [];

export function getAgencyClientById(id: string): AgencyClient | undefined {
  return agencyClients.find((c) => c.id === id);
}

export function getSopById(id: string): Sop | undefined {
  return sops.find((s) => s.id === id);
}
